[package]
name = "ups"
version = "0.0.0"
authors = ["Alejandro Machuca Jiménez <alux6mc@gmail.com>"]
edition = "2024"

[dependencies]
bootloader = "0.9"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
